import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/Navbar";
import GlobalState from "@/context";
import { Inter } from "next/font/google";
import "./globals.css";
// import { NextAuthProviders } from './Providers'
// import "slick-carousel/slick/slick.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <NextAuthProviders> */}
        <GlobalState>
          <Navbar />
          <main className="flex min-h-screen flex-col mt-[64px]">
            {children}
          </main>
          <Footer />
        </GlobalState>
        {/* </NextAuthProviders> */}
      </body>
    </html>
  );
}
